In [2]:
import numpy as np
from datascience import *
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)

# Lesson 5

## Arrays

### 1)

In [7]:
info = make_array("austin","logan","massachusetts","red")
info

array(['austin', 'logan', 'massachusetts', 'red'], dtype='<U13')

#### a)

In [12]:
np.char.upper(info)

array(['AUSTIN', 'LOGAN', 'MASSACHUSETTS', 'RED'], dtype='<U13')

#### b)

In [15]:
np.char.count(info,'a')

array([1, 1, 2, 0])

### 2)

In [23]:
nums = np.arange(1,42,4)
print(nums)
nums = nums.astype(float)
print(nums)

[ 1  5  9 13 17 21 25 29 33 37 41]
[ 1.  5.  9. 13. 17. 21. 25. 29. 33. 37. 41.]


##### a)

In [28]:
print(np.sum(nums))
print(np.prod(nums))

231.0
7579867420125.0


#### b)

In [27]:
print(np.log(nums))

[0.         1.60943791 2.19722458 2.56494936 2.83321334 3.04452244
 3.21887582 3.36729583 3.49650756 3.61091791 3.71357207]
